### ISSUE TITLE
Load listening port from config file in OSC Receiver

### ISSUE THREAD

**Issue by wellis** [bcmodular/scopeosc#1]

**Comment by faxinadu** [comment]
hey dude, when something like my server (or any device that lets the user set ip port and whatnot and has these parameterized) saves this in presets then there is no need for that, imo keep it simple! :)

**Comment by wellis** [comment]
Remember that the OSC Receiver is shared across all Scope devices using the DLL. I'm sure you don't want other developers messing with your system working!

It's trivial to read/write from a config file using Juce, so this is no bother. I'll set a default of 8000 and people will have to find and edit the file in the rare cases where they need to change it.

**Comment by wellis** [comment]
Now reads listener port from C:\Users\xxx\AppData\Roaming\ScopeOSCReceiver\ScopeOSC.settings (or equivalent for different versions of Windows). File is created on first load of OSCReceiver module and will only be re-read at startup, so changing setting will require Scope to be restarted. I'm assuming that this won't be an issue for people as they won't need to change it very often.
